/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.petstore.petstore.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListPetsResponse {
    
    public String contentType;

    public ListPetsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * unexpected error
     */
    
    public com.petstore.petstore.models.shared.Error error;

    public ListPetsResponse withError(com.petstore.petstore.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public ListPetsResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    /**
     * A paged array of pets
     */
    
    public com.petstore.petstore.models.shared.Pet[] pets;

    public ListPetsResponse withPets(com.petstore.petstore.models.shared.Pet[] pets) {
        this.pets = pets;
        return this;
    }
    
    
    public Integer statusCode;

    public ListPetsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListPetsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListPetsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
